services:
    redis:
        container_name: redis_test
        image: redis:8.0-alpine
        command: ["redis-server", "--requirepass", "redis"]
        ports:
            - 6301:6379
        volumes:
            - test_redis_data:/data
    postgres:
        container_name: postgres_test
        image: postgres:17.5-alpine
        restart: unless-stopped
        ports:
            - 5402:5432
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: clove_pg_test
        volumes:
            - test_pgdata:/var/lib/postgresql/data

volumes:
    test_redis_data:
    test_pgdata:
